### PR TITLE
(Feat): Add setup-trunk action

### PR DESCRIPTION
**Pull request by pat-trunk-io**
Factor out trunk-setup

Can be called with:
uses: trunk-io/trunk-action/setup-trunk@v1

### CODE REVIEW

**Comment by EliSchleifer** [comment]
I think we should just call this

uses: trunk-io/trunk-action/setup@v1


so we don't stutter trunk-setup.

And then would be cool to do something like

```
uses: trunk-io/trunk-action/setup@v1
with:
    install: true
```

**Comment by EliSchleifer** [comment]
Any chance we can get this over the line today

**Comment by EliSchleifer** [comment]
Hi Pat - can we get this over the finish line

**Comment by pat-trunk-io** [comment]
Yea I'll get to it yoday

**Review by EliSchleifer — APPROVED** [review]
LGTM. Can we update README with this new verb

**Pull request merged**
