### PR TITLE
feat: add upload_id as a parameter

### PR DESCRIPTION
**Pull request by puzzler7**
Fixes [TRUNK-7654](https://linear.app/trunk/issue/TRUNK-7654/when-check-upload-fails-from-trunk-update-the-ui) and [TRUNK-7716](https://linear.app/trunk/issue/TRUNK-7716/link-to-the-workflow-on-the-first-run), along with [trunk-io/trunk#9735](https://github.com/trunk-io/trunk/pull/9735).

Allows for the check service to create an empty CheckRun, then pass the id to the CLI so it can update it. See [trunk-io/trunk#9735](https://github.com/trunk-io/trunk/pull/9735) for a more detailed explanation.

This PR must go in before [trunk-io/trunk#9735](https://github.com/trunk-io/trunk/pull/9735).

### CODE REVIEW

**Review by sxlijin — APPROVED** [review]
let's also add tests for all.sh, like the ones in trunk_merge.sh

**Review by sxlijin — COMMENTED** [review]
add tests for hold-the-line with no upload id and upload id

see action_tests.yaml

**Comment by puzzler7** [comment]
Is it sufficient to have the old tests without upload id, or did you want me to add new ones?

**Review by sxlijin — APPROVED** [review]

**Comment by sxlijin** [comment]
old tests w/o is sufficient

**Pull request merged**
